# Generated by Django 3.0.4 on 2020-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.IntegerField(max_length=3)),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('calls_answered', models.IntegerField(max_length=6)),
                ('tickets_closed', models.IntegerField(max_length=6)),
                ('average_survey_score', models.FloatField(max_length=6)),
                ('counter_queries_taken', models.IntegerField(max_length=6)),
                ('chats_taken', models.IntegerField(max_length=6)),
                ('breached_tickets', models.IntegerField(max_length=6)),
                ('total_score', models.FloatField(max_length=20)),
            ],
        ),
    ]
