# Generated by Django 3.0.4 on 2020-05-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200414_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='average_survey_score',
        ),
    ]
