# Generated by Django 3.0.4 on 2020-05-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_userdata_average_survey_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
